### ISSUE TITLE
Licence of the code?

### ISSUE THREAD

**Issue by RokerHRO** [TakLun/RC6#1]
I cannot find any license descriptiion. Is it public domain, CC-0, BSD-style license or GPL?

**Comment by EandEBlog** [comment]
This was a university project from many many years ago. I also have not touched this code (or really any part of my repos) at that same amount of time. 

I suppose in that sense, it’s public domain :)

edit: I realize I logged into the wrong account. But message is the same :)

**Comment by RokerHRO** [comment]
So it would be nice if you add an appropriate license file or the like in the repo so I can use (and extend) the code safely. :-)

**Comment by TakLun** [comment]
Done.
